compilers:
  - description: TI C5500 Compiler v4.4.1
    match-compiler-exe: "(.*/)?cl55(.exe)?"
    match-language:  C
    code-insight-target-name: msp430 # Clangd 的目标平台名称
    include-dirs: ${compiler-exe-dir}/../include # 特定于编译器的标头搜索路径
    # 宏定义配置（对象结构）
    defines:
      template: "--define=<NAME>$if(<VALUE>):=<VALUE>"
      separator: " "  # 多个宏之间的分隔符

    # 包含目录配置
    match-args: []